---
- name: Verify Ansible version is greater than 1.8.0 and not 1.9.0
  assert:
    that:
    - ansible_version | version_compare('1.8.0', 'ge')
    - ansible_version | version_compare('1.9.0', 'ne')
    - ansible_version | version_compare('1.9.0.1', 'ne')

- name: Ensure python-netaddr is installed
  yum: pkg=python-netaddr state=installed

- name: Gather Cluster facts
  openshift_facts:
