---
libvirt_storage_pool_path: "{{ lookup('env','HOME') }}/libvirt-storage-pool-openshift-ansible"
libvirt_storage_pool: 'openshift-ansible'
libvirt_network: openshift-ansible
libvirt_uri: 'qemu:///system'

deployment_vars:
  origin:
    image:
      url:    "{{ lookup('oo_option', 'image_url') |
                  default('http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2', True) }}"
      name:   "{{ lookup('oo_option', 'image_name') |
                  default('CentOS-7-x86_64-GenericCloud.qcow2', True) }}"
      sha256: "{{ lookup('oo_option', 'image_sha256') |
                  default('e324e3ab1d24a1bbf035ddb365e7f9058c0b454acf48d7aa15c5519fae5998ab', True) }}"
    ssh_user: openshift
    sudo: yes
  online:
    image:
      url:
      name:
      sha256:
    ssh_user: root
    sudo: no
  enterprise:
    image:
      url:
      name:
      sha256:
    ssh_user: openshift
    sudo: yes
#  origin:
#    fedora:
#      url: "http://download.fedoraproject.org/pub/fedora/linux/releases/21/Cloud/Images/x86_64/Fedora-Cloud-Base-20141203-21.x86_64.qcow2"
#      name: Fedora-Cloud-Base-20141203-21.x86_64.qcow2
#      sha256: 3a99bb89f33e3d4ee826c8160053cdb8a72c80cd23350b776ce73cd244467d86
