---

- name: restart docker
  service: name=docker state=restarted

- name: restart udev
  service:
    name: systemd-udevd
    state: restarted

- name: systemctl daemon-reload
  command: systemctl daemon-reload
