- name: Launch instance(s)
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - set_fact:
        k8s_type: master

    - name: Generate master instance name(s)
      set_fact:
        scratch_name: "{{ cluster_id }}-{{ k8s_type }}-{{ '%05x' | format( 1048576 | random ) }}"
      register: master_names_output
      with_sequence: start=1 end='{{ num_masters }}'

    - set_fact:
        master_names: "{{ master_names_output.results | oo_collect('ansible_facts') | oo_collect('scratch_name') }}"

    - include: launch_instances_tasks.yml
      vars:
        instances: '{{ master_names }}'
        cluster: '{{ cluster_id }}'
        type: '{{ k8s_type }}'
        group_name: 'tag_env-host-type-{{ cluster_id }}-openshift-master'

    - set_fact:
        k8s_type: node

    - name: Generate node instance name(s)
      set_fact:
        scratch_name: "{{ cluster_id }}-{{ k8s_type }}-{{ '%05x' | format( 1048576 | random ) }}"
      register: node_names_output
      with_sequence: start=1 end='{{ num_nodes }}'

    - set_fact:
        node_names: "{{ node_names_output.results | oo_collect('ansible_facts') | oo_collect('scratch_name') }}"

    - include: launch_instances_tasks.yml
      vars:
        instances: '{{ node_names }}'
        cluster: '{{ cluster_id }}'
        type: '{{ k8s_type }}'

# - hosts: 'tag_env-{{ cluster_id }}'
#   roles:
#     - openshift_repos
#     - os_update_latest

# - include: ../openshift-master/config.yml
#   vars:
#     oo_host_group_exp: 'groups["tag_env-host-type-{{ cluster_id }}-openshift-master"]'
#     oo_env: '{{ cluster_id }}'

# - include: ../openshift-node/config.yml
#   vars:
#     oo_host_group_exp: 'groups["tag_env-host-type-{{ cluster_id }}-openshift-node"]'
#     oo_env: '{{ cluster_id }}'
