---
- include: ../../common/openshift-cluster/config.yml
  vars:
    g_etcd_group: "{{ 'etcd' }}"
    g_masters_group: "{{ 'masters' }}"
    g_nodes_group: "{{ 'nodes' }}"
    g_lb_group: "{{ 'lb' }}"
    openshift_cluster_id: "{{ cluster_id | default('default') }}"
    openshift_debug_level: "{{ lookup('oo_option', 'openshift_debug_level') | default('2', True) }}"
    openshift_deployment_type: "{{ deployment_type }}"
