---
# tasks file for docker
- name: Install docker
  action: "{{ ansible_pkg_mgr }} name=docker state=present"

- name: docker systemd unit drop-in directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Configure docker to restart on failures
  template:
    src: restart_on-failure.conf
    dest: /etc/systemd/system/docker.service.d/restart_on-failure.conf
  notify:
  - systemctl daemon-reload
  - restart docker

- name: Use OverlayFS docker backend storage
  lineinfile:
    dest: /etc/sysconfig/docker-storage
    regexp: '^DOCKER_STORAGE_OPTIONS=.*'
    line: "DOCKER_STORAGE_OPTIONS=-s overlay"

- name: enable and start the docker service
  service: name=docker enabled=yes state=started

- include: udev_workaround.yml
  when: docker_udev_workaround | default(False)
