---
# tasks file for docker
- name: Install docker
  action: "{{ ansible_pkg_mgr }} name=docker state=present"

- name: Use OverlayFS docker backend storage
  lineinfile:
    dest: /etc/sysconfig/docker-storage
    regexp: '^DOCKER_STORAGE_OPTIONS=.*'
    line: "DOCKER_STORAGE_OPTIONS=-s overlay"

- name: Use OverlayFS docker backend storage
  lineinfile:
    dest: /etc/sysconfig/docker-storage
    regexp: '^DOCKER_STORAGE_OPTIONS=.*'
    line: "DOCKER_STORAGE_OPTIONS=-s overlay"
  notify:
    - restart docker

- name: enable and start the docker service
  service: name=docker enabled=yes state=started

- include: udev_workaround.yml
  when: docker_udev_workaround | default(False)
