---
debug_level: "{{ lookup('oo_option', 'openshift_debug_level') | default('2', True) }}"

deployment_rhel7_ent_base:
  image: rhel-7
  machine_type: n1-standard-1
  ssh_user: "{{ lookup('env', 'gce_ssh_user') |  default(ansible_ssh_user, true) }}"
  sudo: yes

deployment_vars:
  origin:
    image: centos-7
    machine_type: n1-standard-1
    ssh_user: "{{ lookup('env', 'gce_ssh_user') |  default(ansible_ssh_user, true) }}"
    sudo: yes
  online:
    image: libra-rhel7
    machine_type: n1-standard-1
    ssh_user: root
    sudo: no
  enterprise: "{{ deployment_rhel7_ent_base }}"
  openshift-enterprise: "{{ deployment_rhel7_ent_base }}"
  atomic-enterprise: "{{ deployment_rhel7_ent_base }}"
